version: '3.3'
services:
  db:
    container_name: mikro-orm-tx-tests-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: somepassword
      POSTGRES_DB: test_db
    ports:
      - '15432:5432'
    command: ['postgres', '-c', 'log_statement=all']
